#!/usr/bin/env bash
command='alacritty'
url='https://github.com/alacritty/alacritty/archive/refs/tags/v0.10.1.tar.gz'
checksum='e48d4b10762c2707bb17fd8f89bd98f0dcccc450d223cade706fdd9cfaefb308'
srcDir='alacritty-0.10.1'
dependencies=(
    cmake
    pkg-config
    libfreetype6-dev
    libfontconfig1-dev
    libxcb-xfixes0-dev
    libxkbcommon-dev
    python3
)

install () {
    # Install rust
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source $HOME/.cargo/env
    
    # Build
    cargo build --release -j $(nproc)

    # Copy files
    cp target/release/alacritty /usr/local/bin
    cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
    desktop-file-install extra/linux/Alacritty.desktop
    update-desktop-database
}

uninstall () {
    rm '/usr/local/bin/alacritty'
    rm '/usr/share/pixmaps/Alacritty.svg'
    rm '/usr/share/applications/Alacritty.desktop'
    update-desktop-database
}

cleanup () {
    rustup self uninstall -y
}
